// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFLxws2hbbp_k8MRtYC48mSINcS93DuY0',
    appId: '1:66335158112:web:7b7d9de28986c73f65f805',
    messagingSenderId: '66335158112',
    projectId: 'marketplace-manager-3f89a',
    authDomain: 'marketplace-manager-3f89a.firebaseapp.com',
    storageBucket: 'marketplace-manager-3f89a.firebasestorage.app',
    measurementId: 'G-M27DLD2NME',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFLxws2hbbp_k8MRtYC48mSINcS93DuY0',
    appId: '1:66335158112:web:2ed63b9efae51f8565f805',
    messagingSenderId: '66335158112',
    projectId: 'marketplace-manager-3f89a',
    authDomain: 'marketplace-manager-3f89a.firebaseapp.com',
    storageBucket: 'marketplace-manager-3f89a.firebasestorage.app',
    measurementId: 'G-0SBJJG57K8',
  );
}
